#!/usr/bin/env ruby

$:.unshift File.dirname(__FILE__)

require 'optparse'
require 'functions'

OptionParser.new do |opts|
  opts.banner = "Usage: scythe [options]"

  opts.on("-g", 
          "--gather [project-directory]", 
          "gather probes from source code directory") do |dir|

    project_dir 
      = File.expand_path(dir || ".")

    probe_markers 
      = file_names(project_dir).grep(/\.rb$/)
                               .flat_map {|fn| markers(fn) }

    duplicated_markers 
      = probe_markers.group_by {|m| m }
                     .select {|_,v| v.length > 1 }
                     .keys

    unless duplicated_markers.empty?
      puts "Markers found more than once in #{project_dir}:\n"
      puts "\n#{duplicated_markers.join($/)}\n\n" 
      exit(1)
    end

    probe_markers.uniq.each do |marker|
      record_marker(marker)
    end
  end


  opts.on("-s",
          "--status",
          "show status of probes") do

    now = Time.now.to_i

    file_names(".").grep(/\.scythe_marker/)
                   .map {|n| File.basename(n,".*") }
                   .map {|n| [n,File.mtime(n)] }
                   .sort_by {|name,time| [time-now,name] }
    

  end

end.parse!



